//Author: Francesco Pizzato

#include "../include/readJSON.h"
#include "../include/CardRectifier.h"
#include "../include/CardRecognizer.h"
#include "../include/MatchTheory.h"
#include "../include/Print.h"
#include "../include/FixedMatch.h"
#include "../include/PerformanceMeasurement.h"

//main: launch YOLO, readJSON, watch frames, rectify, recognize, rebuild the game.
// it crerates a csv in ../output and compares it to the ground truth csv
//How to use it:  ./main [game]      (default: game1)
//the json is generated by CardDetector.py only if missing, delete it to run yolo again
int main(int argc, char** argv)
{
    //game passed as argument, e.g. ./main game3 (default game1)
    std::string game = "game1";
    if (argc > 1){
        game = argv[1];
    }
        
    std::string jsonPath = "../json/" + game + ".json";

    //explanation of how the program works
    printIntro(game);

    //1. detection
    std::cout << "[1/4] Detection" << std::endl;

    //if the json of the game does not exist, run CardDetector.py to create it (yolo is slow)
    if (!std::filesystem::exists(jsonPath)) {
        std::cout << "      json not found, running YOLO on " << game << " (it takes some minutes)..." << std::endl;

        //python is the python of the system (it must have ultralytics and opencv installed)
        std::string command = "python3 ../src/CardDetector.py " + game; //'python' if windows 
        std::system(command.c_str());

        //python not found or yolo failed: the json is still missing
        if (!std::filesystem::exists(jsonPath)) {
            std::cerr << "Cannot create " << jsonPath << ": run by hand  python3 CardDetector.py " << game << "  in the src folder" << std::endl;
            return 1;
        }
    }
    std::cout << "      cards found by YOLO: " << jsonPath << std::endl;

    //2. recognition
    std::cout << "\n[2/4] Recognition" << std::endl;

    //load the 40 templates once
    std::vector<CardTemplate> templates = loadTemplates();
    std::cout << "      templates loaded: " << templates.size() << "/41 (40 cards + card back)" << std::endl;
    if (templates.empty()) {
        std::cerr << "No templates loaded." << std::endl;
        return 1;
    }

    //read all detected cards from the json (one entry per card: round, frame, corners)
    std::vector<JSONCardInfo> cards = readJSON(jsonPath);
    std::cout << "      cards to recognize: " << cards.size() << std::endl;

    //number of rounds, only for the progress line
    int nRounds = 0;
    for (const JSONCardInfo& card : cards)
        nRounds = std::max(nRounds, card.round);

    int currentRound = -1;
    int currentFrame = -1;
    cv::VideoCapture cap;
    cv::Mat frame;

    //every recognized card, with its position, for MatchTheory
    std::vector<CardDetection> detections;

    //for every detected card on the JSON, using the real frames rectify it and recognize it against the templates
    for (const JSONCardInfo& card : cards) {

        //open the round video when the round changes
        if (card.round != currentRound) {
            currentRound = card.round;
            currentFrame = -1;
            std::string videoPath = "../data/videos/" + game + "/" + game
                                  + "round" + std::to_string(card.round) + ".mp4";
            cap.open(videoPath);
            if (!cap.isOpened()) {
                std::cerr << "\nCannot open video: " << videoPath << std::endl;
                continue;
            }
            //progress on one line: \r goes back to the start of the line
            std::cout << "\r      reading the videos: round " << card.round << "/" << nRounds << std::flush;
        }

        //grab the frame only when it changes (cards of the same frame are consecutive)
        if (card.frame != currentFrame) {
            currentFrame = card.frame;
            cap.set(cv::CAP_PROP_POS_FRAMES, card.frame);
            cap.read(frame);
        }
        if (frame.empty()) continue;

        //rectify the card with its corner
        cv::Mat warped = rectify(frame, card.corners);
        cv::Mat gray;
        cv::cvtColor(warped, gray, cv::COLOR_BGR2GRAY);

        //recognize it against the templates
        int label = recognize(gray, templates);

        //save the card as CardDetection for MatchTheory (round, frame, label, center)
        CardDetection detection;
        detection.round = card.round;
        detection.frame = card.frame;
        detection.label = label;
        detection.center = cv::Point2f(0.f, 0.f);
        for (const cv::Point& p : card.corners)
            detection.center += cv::Point2f((float) p.x, (float) p.y);
        detection.center *= (1.0f / (float) card.corners.size());
        detections.push_back(detection);
    }
    std::cout << std::endl;

    //3. game: briscola, cards of every round, players, leader, winner, points
    //(it needs all the rounds together, so the results are printed at the end)
    std::cout << "\n[3/4] Game reconstruction" << std::endl << std::endl;
    std::vector<RoundResult> results = analyzeMatch(detections);

    //csv in the ground truth format
    std::filesystem::create_directories("../output");
    std::string csvPath = "../output/" + game + "_output.csv";
    if (!writeCSV(results, csvPath)) {
        std::cerr << "Cannot write " << csvPath << std::endl;
        return 1;
    }

    //read the csv back: the same rows are shown on screen and used for the metrics
    std::vector<RoundRow> predicted = readResultsCSV(csvPath);
    printGame(game, predicted, std::cout);
    std::cout << "\nCSV: " << csvPath << std::endl;

    //4. evaluation
    std::cout << "\n[4/4] Performance measurement" << std::endl;

    //performance measurement: compare the csv with the ground truth
    std::string gtPath = "../data/ground_truth/" + game + "resultsCORRECTED.csv";
    if (!std::filesystem::exists(gtPath))
        gtPath = "../data/ground_truth/" + game + "results.csv";
    if (argc > 2)
        gtPath = argv[2];
    std::cout << "      ground truth: " << gtPath << std::endl;

    try {
        std::vector<RoundRow> groundTruth = readResultsCSV(gtPath);

        Metrics metrics = evaluateGame(predicted, groundTruth);
        std::cout << std::endl;
        printMetrics(game, metrics, std::cout);

        std::string metricsPath = "../output/" + game + "_metrics.txt";
        if (writeMetrics(game, metrics, metricsPath))
            std::cout << "Metrics: " << metricsPath << std::endl;
        else
            std::cerr << "Cannot write " << metricsPath << std::endl;
    } catch (const std::runtime_error& e) {
        std::cerr << "Performance measurement skipped: " << e.what() << std::endl;
    }

    return 0;
}
